name: 'Mirror repository'
description: 'Mirror github to another location, if the repository does not exist, it will be created automatically'
branding:
  icon: 'copy'
  color: 'green'
inputs:
  ssh_private_key:
    description: 'SSH private key'
    required: true
  repo:
    description: 'SSH repo url'
    required: true
    default: ${{ github.event.repository.ssh_url }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.repo }}
