name: 💕 mirror

on:
  push:
    branches:
      - master
      - dev

jobs:
  mirror:
    name: 💕 mirror to another location
    runs-on: ubuntu-latest
    steps:
      - name: 💕 mirror
        uses: csplink/action_git_mirror/@dev
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
